<html>
<head>
<title>PREFEITURA DO MUNICÍPIO DE ROLANDIA</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<frameset rows="130,*" frameborder="NO" border="0" framespacing="0">
  <frame src="http://www.viasulvirtual.com.br/prefeitura/rolandia/topo/topo.htm" name="topFrame" scrolling="NO" noresize >
  <frame src="http://www.viasulvirtual.com.br/net10/site/default.asp?cliente=rolandia&idfam=<%= Request.QueryString("idfam") %>&ultimas_fixa=true" name="mainFrame">
</frameset>
<noframes><body>
Se você está vendo esta página, seu navegador não suporta frames. Para visualizar este site é recomendável IE5 ou maior.
</body></noframes>
</html>