<%
nome_banco = "database/" & cliente & "/banco.mdb"
'caminho_dados = "c:\export\users\ftpnet10\database\"
'caminho_dados_local = "C:\Inetpub\Em_Andamento\net10\Site\database\"
caminho_dados = "C:\Inetpub\Em_Andamento\net10\Site\database\"

pasta_wwwroot = "\wwwroot"
caminho_pasta_clientes = "\clientes\site\home\clientes\"

'Caminho para todas as URLs do site
endereco_virtual = "http://www.net10.com.br/clientes/site/"

'Endereco_cliente mostra a pasta onde ficarão os arquivos do cliente 
'Serve também para os IFRAMES (Menu_lateral, Noticias_rotativas, etc)
endereco_cliente = "http://www.net10.com.br/clientes/site/home/clientes/"

%>