<html>
<head>
<title>Erro</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table width="100%" border="0" cellspacing="0">
<tr>
<td>
<table width="60%" border="0" cellspacing="0" align="center">
<tr> 
<td bgcolor="#3399CC"> 
<center>
<b><font face="Arial, Helvetica, sans-serif" color="#FFFFFF">Aten&ccedil;&atilde;o:</font></b> 
</center>
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
<tr> 
<td> 
<center>
<b><font color="#990000" face="Arial, Helvetica, sans-serif">Usu&aacute;rio ou 
senha n&atilde;o coincidem.</font></b> 
</center>
</td>
</tr>
<tr> 
<td>&nbsp;</td>
</tr>
<tr> 
<td> 
<div align="right"><font face="Arial, Helvetica, sans-serif" size="2"><a href="javascript:history.go(-1)">Clique 
aqui para voltar e tentar novamente.</a></font></div>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>
